{{- if .Values.configs.cosign_deploy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configs.cosign_deploy.name }}
  namespace: {{ .Values.configs.cosign_deploy.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.configs.cosign_deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.configs.cosign_deploy.name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65533
      {{- if $.Values.configs.cosign_deploy.rolebindings }}
      serviceAccountName: {{ index .Values.configs.cosign_deploy.rolebindings 0 }}
      {{- end }}
      containers:
      - args:
        - -c
        - cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json; while true; do sleep 86400; done
        command:
        - /bin/sh
        name: {{ .Values.configs.cosign_deploy.name }}
        image: "{{ .Values.configs.cosign_deploy.image.registry }}/{{ .Values.configs.cosign_deploy.image.repository }}:{{ .Values.configs.cosign_deploy.image.version }}"
        env:
        - name: OPENSHIFT_APPS_SUBDOMAIN
          value: {{ .Values.global.appsSubdomain }}
        - name: OIDC_AUTHENTICATION_REALM
          value: "sigstore"
        - name: FULCIO_URL
          value: "https://fulcio.$(OPENSHIFT_APPS_SUBDOMAIN)"
        - name: OIDC_ISSUER_URL
          value: "https://keycloak-keycloak-system.$(OPENSHIFT_APPS_SUBDOMAIN)/auth/realms/$(OIDC_AUTHENTICATION_REALM)"
        - name: REKOR_URL
          value: "https://rekor.$(OPENSHIFT_APPS_SUBDOMAIN)"
        - name: TUF_URL
          value: "https://tuf.$(OPENSHIFT_APPS_SUBDOMAIN)"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
{{- end }}
